### PR TITLE
feat(infra): add mlflow server for rag evaluation

### PR DESCRIPTION
**Pull request by jslecointre**
Add mlflow infra for tracking RAG evaluation metrics

### CODE REVIEW

**Comment by jslecointre** [comment]
Below are the new environment variables :

_for the mlflow server :_

```
AWS_ACCESS_KEY_ID=<IBM cloud bucket key ID>
MLFLOW_BUCKET_ENDPOINT=s3://<IBM cloud bucket name> # use for artifacts,images,files to be stored as part of evals
AWS_SECRET_ACCESS_KEY=<IBM cloud bucket secret key>
MLFLOW_S3_ENDPOINT_URL=<IBM cloud bucket url>
AWS_DEFAULT_REGION=<IBM cloud region>
```

_for the backend :_

```
AWS_ACCESS_KEY_ID=<IBM cloud bucket key ID>
AWS_SECRET_ACCESS_KEY=<IBM cloud bucket secret key>
AWS_DEFAULT_REGION=<IBM cloud region>
MLFLOW_BUCKET_ENDPOINT=s3://<IBM cloud bucket name>
MLFLOW_TRACKING_URI=<mlflow server url>
MLFLOW_S3_ENDPOINT_URL=<IBM cloud bucket url>
GIT_PYTHON_REFRESH=quiet
```

**Comment by mtykhenko** [comment]
What is desired value of $MLFLOW_VERSION?
Can we have it static in Dockerfile?

**Comment by mtykhenko** [comment]
Please move mlflow-server build configuration out to docker compose file.
We may not use docker compose everywhere but build is required always

**Comment by jslecointre** [comment]
I removed mlflow build out of the docker compose and added `build-mlflow` in Makefile.

I also enabled basic authentication with `admin` user - we can change the admin password once the server will be started.

**Comment by manavgup** [comment]
Closing as completed. Model fallback mechanism has been implemented in LLM provider system with proper error handling and retry logic.

**Pull request merged**
